### ISSUE TITLE
Some icons are missing/replaced by plain text

### ISSUE THREAD

**Issue by humanplayer2** [pangchj/public#1]
Thank you for this! I just tried the solution on the LyX wiki with unusable results and then found this.

Under KDE 5.18, I see behavior which indicates some missing icons perhaps?
Some icons are simply replaced by plain text descriptions. This includes "Spellcheck continuously", "Find and replace", "Set display mode", "Superscript", "Subscript", "Insert delimiters", "Insert matrix" ...

**Comment by pangchj** [comment]
I replaced the images in the "images" directory (but not the subdirectories) with the original SVGZ files. You can try that and see whether it is better for you. I know that it doesn't work 100% (Some SVGZ icons in the original directory are still dark). Maybe will work on it later...

**Comment by humanplayer2** [comment]
It is definitely better!
I see that there are still some non-dark icons that are not as visible, but so far, I see only improvements over the default.

**Comment by pangchj** [comment]
Perhaps your issues will be all resolved with the "Classic" icon set? It would be difficult to invert the colors of the Oxygen and Default icon sets as they are SVGZ files. In my Ubuntu 20.04 setup with LyX 2.3.4.2, I got "Spellcheck continuously" as text in the first version, but the others that you mentioned appear as icons (and not text) in the "Classic" icon set (which has its colors inverted).

I guess in the worst case, you can take the shell scripts inside ./images , ./images/ipa and ./images/math (in the latest version of lyx_images.zip) to customize your solution.
